// Mocks generated by Mockito 5.1.0 from annotations
// in foods/test/model/api/user_api_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:foods/model/api/user_api.dart' as _i2;
import 'package:foods/model/user_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [UserAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserAPI extends _i1.Mock implements _i2.UserAPI {
  MockUserAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.UserModel>> getUser() =>
      (super.noSuchMethod(Invocation.method(#getUser, []),
              returnValue: Future<List<_i4.UserModel>>.value(<_i4.UserModel>[]))
          as _i3.Future<List<_i4.UserModel>>);
  @override
  _i3.Future<dynamic> postUsers(_i4.UserModel? user) =>
      (super.noSuchMethod(Invocation.method(#postUsers, [user]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
}
